WebApplication/Controllers/UploadController.cs
using System;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class UploadController : Controller
    {
        private readonly FilesDbContext _context;
        private readonly ILogger<UploadController> _logger;

        public UploadController(FilesDbContext context, ILogger<UploadController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> UploadFile(FormModel model)
        {

            List<IFormFile> files = model.files;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var filePaths = new List<string>();
            foreach (IFormFile formFile in files)
            {
                
                    if (formFile.Length > 0)
                    {
                        string filePath = Path.Combine(Path.GetFullPath("StorageFiles"), userId + Path.GetFileName(formFile.FileName));
                        filePaths.Add(filePath);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                        }

                        _logger.LogTrace(message: $"Logging User Identity: {User.Identity?.ToString()}");
                        var f = new WebApp.Models.File()
                        {
                            Name = formFile.FileName,
                            Created = DateTime.Now,
                            Size = (int)formFile.Length,
                            Path = Path.GetFileName(filePath),
                            UserId = userId,
                        };
                        _context.Add(f);
                        _context.SaveChanges();
                    }
                
            }
            return Redirect("/"); ;
        }

        [Authorize]
        public ActionResult Download(string path)
        {
            string fullName = Path.Combine(Path.GetFullPath("StorageFiles"), path);
            System.IO.FileStream fs = System.IO.File.OpenRead(fullName);
            byte[] data = new byte[fs.Length];
            int br = fs.Read(data, 0, data.Length);
            if (br != fs.Length)
                throw new System.IO.IOException(fullName);
            return File(
                data, System.Net.Mime.MediaTypeNames.Application.Octet, "Download" + "." + path.Split(".")[1]);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Deloitte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Upload" asp-action="UploadFile">Upload</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="mt-auto">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
           &copy;Deloitte.com | 2022 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>